
FROM python:3.10-slim

ENV PIP_NO_CACHE_DIR=1 PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt /app/
RUN apt-get update && apt-get install -y --no-install-recommends         gcc g++ build-essential     && pip install -U pip     && pip install -r requirements.txt     && apt-get purge -y --auto-remove gcc g++ build-essential     && rm -rf /var/lib/apt/lists/*

COPY server.py /app/

EXPOSE 8200
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8200"]
